CREATE TABLE settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    bed_count INTEGER NOT NULL DEFAULT 4 CHECK (bed_count BETWEEN 2 AND 8)
);

INSERT INTO settings (id, bed_count) VALUES (1, 4);

ALTER TABLE beds ADD COLUMN prep_min INTEGER NOT NULL DEFAULT 0 CHECK (prep_min BETWEEN 0 AND 9);
ALTER TABLE beds ADD COLUMN cool_min INTEGER NOT NULL DEFAULT 0 CHECK (cool_min BETWEEN 0 AND 5);
ALTER TABLE beds ADD COLUMN picture_path TEXT NOT NULL DEFAULT '';

ALTER TABLE sessions ADD COLUMN prep_min INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN cool_min INTEGER NOT NULL DEFAULT 0;
